### ISSUE TITLE
multiple issues

### ISSUE THREAD

**Issue by bnomei** [lukasbestle/shareable#1] opened 2018-11-27 11:16 UTC
file permissions 644/755 are set. config edited. php 7.2 apache (verified).

sadly i can not get sharable to run.
- setting password does not work. login fails without error. used `password_hash('mypassword', PASSWORD_DEFAULT);` in another php file to generate the string
- inbox returns http status code 500 (debug does not help). even for anonymous login with all permissions.
- cron job is called with non php <7.2 version but that might be my host fault and fails in line 13

**Comment by bnomei** [comment] 2018-11-27 11:16
i did contact you with more details in getkirby/slack to avoid spamming here.

**Comment by bnomei** [comment] 2018-11-27 13:03
seems to be related to apache and htaccess. since it works on nginx (tested via valet).

**Comment by lukasbestle** [comment] 2018-11-27 18:34
As I wrote on Slack already, it can't be Apache (I'm using it on Apache as well).
If the `FallbackResource` doesn't work for you, you can also use a more traditional `RewriteRule` like for Kirby, that should work too.

I'm closing this issue for now as we don't know yet where the issue is (in Shareable or in the setup at your hosting provider). Feel free to reopen or open a new issue once you have more insights (like an error message or even better a full backtrace). :)

**Closed as completed by lukasbestle** 2018-11-27 18:34 UTC
